### ISSUE TITLE
Unreadable dark text on dark background in pkgdown navbar

### ISSUE THREAD

**Issue by jadeynryan** [WA-Department-of-Agriculture/soils#4]
Known issue. Setting `type: light` or `type:dark` does not help. Will have to wait until pkgdown has fixed https://github.com/r-lib/pkgdown/issues/2387. Tan submitted a PR fix https://github.com/r-lib/pkgdown/pull/2388.

**Comment by tanho63** [comment]
popping by to say this got merged into pkgdown-main :grinning:

**Comment by jadeynryan** [comment]
Thanks @tanho63! I updated {pkgdown} to the dev version, rebuilt the site, and then redeployed. But the navbar text is still black. Do you have any suggestions?

**Comment by tanho63** [comment]
Two things to change: instead of any::pkgdown you should use r-lib/pkgdown, and add `type: dark` under navbar in your pkgdown.yml https://pkgdown.r-lib.org/articles/customise.html#navbar-style

**Comment by jadeynryan** [comment]
Thank you SO much! You're the best. ☺
